<form class="login">
  <div class="form-group">
    <label for="email">Email address</label>
    <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
  </div>

  <div class="form-group">
    <label for="message">Message</label>
    <textarea class="form-control" id="message" rows="3"></textarea>
  </div>
    <input type="submit" class="btn btn-primary">
</form>
<br><br><br><br><br><br><br><br><br>