<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Boutique myProtein</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../css/styles.css"/>
    <link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet"> 
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="stylesheet" href="../plugin/flexslider.css" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
    <script src="../plugin/jquery.flexslider.js"></script>
    <script type="text/javascript" charset="utf-8">

          $(window).load(function() {
            $('.flexslider').flexslider();
          });
        </script>
</head>
<body>
    <header>
        <?php 

        if (isset($_SESSION['id'])): ?>
            <div class="bonjour">
                <p style="color:white;">
                    <?= 'Bonjour ' . $_SESSION['firstname']; ?>
                    <a href="panier.php" class="display">Mon panier
                    <span style="color:white;"> 
                        ( 
                        <?php  
                            if (isset($_SESSION['panier']) == false) {
                                 $_SESSION['panier'] = [];       
                                }
                            $c = count($_SESSION["panier"]); 
                        ?> 
                            <?= $c; ?> 
                        ) 
                    </span> 
                    <i class="fas fa-shopping-cart"></i> </a> /
                    <a href="compte.php" class="display">Mon compte </a> / 
                    <a href="deconnection.php" class="display">Deconnection</a>
                </p>
                <style>
                    .hidden {
                        display: none;
                    }
                    .display {
                        padding-left: 2rem;
                    }
                </style>
            </div>
            <?php endif ?>
            <?php if(empty($_SESSION["id"])): ?>
                    <style>
                    .hidden {
                        display: block!IMPORTANT;
                    }
                    </style>
                <?php endif ?>



        <nav>
            <ul>
                <li><a href="home.php">Accueil</a></li>
                <li><a href="shop.php">Boutique</a></li>
                <li><a href="contact.php">Nous contacter</a></li>
                <li><a href="login.php" class="hidden">Login</a></li>
                <li><a href="signUp.php" class="hidden">S'enregistrer</a></li>
            </ul>
        </nav>
        
    </header>