<main class="container">
	<h1>Se connecter</h1>
	<div class="login">
		<form class="form-group" method="POST" action="../public/processLogin.php">
			<label for="email">Email : </label>
			<input type="email" name="email" class="form-control" placeholder="Votre email">
			<label for="password">Password : </label>
			<input type="password" name="password" class="form-control" placeholder="Password"><br><br>
			<input type="submit" name="submit" class="btn btn-success">
		</form>
		<p>Vous n'avez pas de compte ?</p>
		<a href="signIn.php" class="btn btn-primary">S'enregistrer</a>
	</div>

	<br><br><br><br><br><br><br><br>

</main>