<main class="container">
	<h1>S'enregistrer</h1>
	<div class="login">
		<form class="form-group" method="POST" action="../public/processSignIn.php">
			<label for="email">Email : </label>
			<input type="email" name="email" class="form-control" placeholder="Votre email"><br>
			<label for="firstname">Firstname : </label>
			<input type="text" name="firstname" class="form-control" placeholder="Votre prénom"><br>
			<label for="lastname">Lastname : </label>
			<input type="text" name="lastname" class="form-control" placeholder="Votre prénom"><br>
			<label for="password">Password : </label>
			<input type="password" name="password" class="form-control" placeholder="Password"><br>
			<label for="password">Password : </label>
			<input type="password" name="password" class="form-control" placeholder="confirm password"><br>
			<input type="submit" name="submit" class="btn btn-success" value="s'enregistrer">
		</form>
	</div>

	<br><br><br><br><br><br><br><br>

</main>